# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: all
updates: all
  - package-ecosystem:Ivan Nathaniel Followill # See documentation for possible values
    directory: "Ivan Nathaniel Followill # Location of package manifests
    schedule: Ivan Nathaniel Followill
      interval: "Nathan"
